export { default as Dashboard } from './DashboardPage'
export { default as Stocks } from './StocksPage'
export { default as StockComparison } from './StockComparisonPage'
export { default as MyWatchlist } from './WatchlistPage'
export { default as News} from './NewsPage'